import {
  GraduationCap,
  BookOpen,
  BookCheck,
  Library,
  Telescope,
  Trophy,
  Zap,
  FlaskConical,
  TestTubeDiagonal,
  Microscope,
  Atom,
  Cpu,
  Terminal,
  Crown,
  Crosshair,
  Target,
  Map,
  Route,
  Navigation,
  Shield,
  ScanSearch,
  Search,
  Flame,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  Dumbbell,
  Infinity,
  Coins,
  Star,
  Gem,
  Sparkles,
  Wand2,
  Medal,
  Award,
  Users,
  Clock,
  Timer,
  Rocket,
  Moon,
  Sun,
  RefreshCcw,
  Fingerprint,
  ClipboardCheck,
  Share2,
  UserCheck,
  EyeOff,
  Languages,
  Gift,
  ShieldCheck,
} from 'lucide-react';
import type {
  BadgeSlug,
  BadgeVisualConfig,
  TierDesign,
} from '../types/badge.types';

// ═══ Tier Design Tokens ═══════════════════════════════════════════════════
export const TIER_DESIGNS: Record<string, TierDesign> = {
  BRONZE: {
    bg: 'from-amber-950 via-orange-900/80 to-amber-950',
    ring: 'ring-amber-600/60',
    iconColor: 'text-amber-400',
    glowColor: 'shadow-amber-700/50',
    label_en: 'Bronze',
    label_ar: 'برونزي',
  },
  SILVER: {
    bg: 'from-zinc-800 via-slate-700/90 to-zinc-800',
    ring: 'ring-zinc-400/50',
    iconColor: 'text-zinc-200',
    glowColor: 'shadow-zinc-500/40',
    label_en: 'Silver',
    label_ar: 'فضي',
  },
  GOLD: {
    bg: 'from-yellow-950 via-amber-700/80 to-yellow-950',
    ring: 'ring-yellow-500/60',
    iconColor: 'text-yellow-300',
    glowColor: 'shadow-yellow-600/60',
    label_en: 'Gold',
    label_ar: 'ذهبي',
  },
  PLATINUM: {
    bg: 'from-cyan-950 via-teal-700/80 to-cyan-950',
    ring: 'ring-cyan-400/60',
    iconColor: 'text-cyan-200',
    glowColor: 'shadow-cyan-600/60',
    label_en: 'Platinum',
    label_ar: 'بلاتيني',
  },
  DIAMOND: {
    bg: 'from-violet-950 via-purple-700/80 to-violet-950',
    ring: 'ring-violet-400/70',
    iconColor: 'text-violet-200',
    glowColor: 'shadow-violet-600/70',
    label_en: 'Diamond',
    label_ar: 'ألماس',
  },
};

// ═══ Badge Registry (50 Badges) ═══════════════════════════════════════════
export const BADGE_REGISTRY: Partial<Record<BadgeSlug, BadgeVisualConfig>> = {
  // ─── Learning ────────────────────────────────────────────────────────────
  FIRST_COURSE: {
    icon: GraduationCap,
    tier: 'BRONZE',
    category: 'learning',
    label_en: 'First Step',
    label_ar: 'الخطوة الأولى',
    desc_en: 'Completed your very first course.',
    desc_ar: 'أكملت أول كورس لك على المنصة.',
  },
  COURSE_3: {
    icon: BookOpen,
    tier: 'BRONZE',
    category: 'learning',
    label_en: 'Triple Scholar',
    label_ar: 'ثلاثي التعلم',
    desc_en: 'Completed 3 courses.',
    desc_ar: 'أكملت 3 كورسات.',
  },
  COURSE_5: {
    icon: BookCheck,
    tier: 'SILVER',
    category: 'learning',
    label_en: 'Knowledge Seeker',
    label_ar: 'طالب المعرفة',
    desc_en: 'Completed 5 courses.',
    desc_ar: 'أكملت 5 كورسات.',
  },
  COURSE_10: {
    icon: Library,
    tier: 'SILVER',
    category: 'learning',
    label_en: 'Cyber Student',
    label_ar: 'طالب السايبر',
    desc_en: 'Completed 10 courses.',
    desc_ar: 'أكملت 10 كورسات.',
  },
  COURSE_25: {
    icon: Telescope,
    tier: 'GOLD',
    category: 'learning',
    label_en: 'Scholar',
    label_ar: 'العالِم',
    desc_en: 'Completed 25 courses.',
    desc_ar: 'أكملت 25 كورس.',
  },
  COURSE_ALL: {
    icon: Trophy,
    tier: 'DIAMOND',
    category: 'learning',
    label_en: 'Completionist',
    label_ar: 'المكتمل',
    desc_en: 'Completed every available course.',
    desc_ar: 'أكملت جميع الكورسات المتاحة.',
  },
  SPEED_RUNNER: {
    icon: Zap,
    tier: 'GOLD',
    category: 'learning',
    label_en: 'Speed Runner',
    label_ar: 'سريع التعلم',
    desc_en: 'Completed a full course in under 24 hours.',
    desc_ar: 'أكملت كورساً كاملاً في أقل من 24 ساعة.',
  },

  // ─── Labs ────────────────────────────────────────────────────────────────
  FIRST_LAB: {
    icon: FlaskConical,
    tier: 'BRONZE',
    category: 'labs',
    label_en: 'Lab Initiate',
    label_ar: 'مبتدئ المختبر',
    desc_en: 'Solved your first lab.',
    desc_ar: 'حللت أول لاب.',
  },
  LAB_3: {
    icon: TestTubeDiagonal,
    tier: 'BRONZE',
    category: 'labs',
    label_en: 'Lab Explorer',
    label_ar: 'مستكشف المختبر',
    desc_en: 'Solved 3 labs.',
    desc_ar: 'حللت 3 لابات.',
  },
  LAB_5: {
    icon: Microscope,
    tier: 'SILVER',
    category: 'labs',
    label_en: 'Analyst',
    label_ar: 'المحلل',
    desc_en: 'Solved 5 labs.',
    desc_ar: 'حللت 5 لابات.',
  },
  LAB_10: {
    icon: Search,
    tier: 'SILVER',
    category: 'labs',
    label_en: 'Researcher',
    label_ar: 'الباحث',
    desc_en: 'Solved 10 labs.',
    desc_ar: 'حللت 10 لابات.',
  },
  LAB_25: {
    icon: Atom,
    tier: 'GOLD',
    category: 'labs',
    label_en: 'Lab Expert',
    label_ar: 'خبير المختبر',
    desc_en: 'Solved 25 labs.',
    desc_ar: 'حللت 25 لاب.',
  },
  LAB_50: {
    icon: Cpu,
    tier: 'PLATINUM',
    category: 'labs',
    label_en: 'Hacker Elite',
    label_ar: 'نخبة الهاكر',
    desc_en: 'Solved 50 labs.',
    desc_ar: 'حللت 50 لاب.',
  },
  LAB_100: {
    icon: Terminal,
    tier: 'DIAMOND',
    category: 'labs',
    label_en: 'Grand Hacker',
    label_ar: 'الهاكر الكبير',
    desc_en: 'Solved 100 labs.',
    desc_ar: 'حللت 100 لاب.',
  },
  HACK_KING: {
    icon: Crown,
    tier: 'DIAMOND',
    category: 'labs',
    label_en: 'Hack King',
    label_ar: 'ملك الهكر',
    desc_en: 'Solved 5 labs in a single day.',
    desc_ar: 'حللت 5 لابات في يوم واحد.',
  },
  FIRST_BLOOD: {
    icon: Crosshair,
    tier: 'GOLD',
    category: 'labs',
    label_en: 'First Blood',
    label_ar: 'أول دم',
    desc_en: 'First person to solve a specific lab.',
    desc_ar: 'أول شخص يحل لاباً معيناً.',
  },
  PERFECT_SOLVE: {
    icon: Target,
    tier: 'GOLD',
    category: 'labs',
    label_en: 'Flawless',
    label_ar: 'بلا أخطاء',
    desc_en: 'Solved a lab on the very first attempt.',
    desc_ar: 'حللت لاباً من أول محاولة.',
  },

  // ─── Paths ───────────────────────────────────────────────────────────────
  FIRST_PATH: {
    icon: Map,
    tier: 'BRONZE',
    category: 'paths',
    label_en: 'Pathfinder',
    label_ar: 'مكتشف المسارات',
    desc_en: 'Completed your first learning path.',
    desc_ar: 'أكملت أول مسار تعليمي.',
  },
  PATH_3: {
    icon: Route,
    tier: 'SILVER',
    category: 'paths',
    label_en: 'Road Warrior',
    label_ar: 'محارب الطريق',
    desc_en: 'Completed 3 learning paths.',
    desc_ar: 'أكملت 3 مسارات تعليمية.',
  },
  PATH_ALL: {
    icon: Navigation,
    tier: 'DIAMOND',
    category: 'paths',
    label_en: 'Path Master',
    label_ar: 'سيد المسارات',
    desc_en: 'Completed all available learning paths.',
    desc_ar: 'أكملت جميع المسارات التعليمية.',
  },
  PATH_WEB_SEC: {
    icon: Shield,
    tier: 'PLATINUM',
    category: 'paths',
    label_en: 'Web Guardian',
    label_ar: 'حارس الويب',
    desc_en: 'Completed the Web Security path.',
    desc_ar: 'أكملت مسار أمن الويب.',
  },
  PATH_PENTEST: {
    icon: ScanSearch,
    tier: 'PLATINUM',
    category: 'paths',
    label_en: 'Pen Tester',
    label_ar: 'مختبر الاختراق',
    desc_en: 'Completed the Penetration Testing path.',
    desc_ar: 'أكملت مسار اختبار الاختراق.',
  },
  PATH_FORENSICS: {
    icon: Microscope,
    tier: 'PLATINUM',
    category: 'paths',
    label_en: 'Forensic Analyst',
    label_ar: 'المحقق الرقمي',
    desc_en: 'Completed the Digital Forensics path.',
    desc_ar: 'أكملت مسار الجنائيات الرقمية.',
  },

  // ─── Streak ──────────────────────────────────────────────────────────────
  STREAK_3: {
    icon: Flame,
    tier: 'BRONZE',
    category: 'streak',
    label_en: 'On Fire',
    label_ar: 'في حماسة',
    desc_en: '3-day learning streak.',
    desc_ar: '3 أيام متتالية من التعلم.',
  },
  STREAK_7: {
    icon: CalendarCheck,
    tier: 'SILVER',
    category: 'streak',
    label_en: 'Week Warrior',
    label_ar: 'محارب الأسبوع',
    desc_en: '7-day learning streak.',
    desc_ar: '7 أيام متتالية من التعلم.',
  },
  STREAK_14: {
    icon: CalendarDays,
    tier: 'SILVER',
    category: 'streak',
    label_en: 'Fortnight',
    label_ar: 'نصف الشهر',
    desc_en: '14-day learning streak.',
    desc_ar: '14 يوماً متتالياً من التعلم.',
  },
  STREAK_30: {
    icon: CalendarRange,
    tier: 'GOLD',
    category: 'streak',
    label_en: 'Dedicated',
    label_ar: 'المثابر',
    desc_en: '30-day learning streak.',
    desc_ar: '30 يوماً متتالياً من التعلم.',
  },
  STREAK_60: {
    icon: Dumbbell,
    tier: 'PLATINUM',
    category: 'streak',
    label_en: 'Iron Will',
    label_ar: 'إرادة من حديد',
    desc_en: '60-day learning streak.',
    desc_ar: '60 يوماً متتالياً من التعلم.',
  },
  STREAK_100: {
    icon: Infinity,
    tier: 'DIAMOND',
    category: 'streak',
    label_en: 'Unstoppable',
    label_ar: 'لا يُوقَف',
    desc_en: '100-day learning streak.',
    desc_ar: '100 يوم متتالي من التعلم.',
  },

  // ─── XP ──────────────────────────────────────────────────────────────────
  XP_500: {
    icon: Coins,
    tier: 'BRONZE',
    category: 'xp',
    label_en: 'XP Starter',
    label_ar: 'بداية الـ XP',
    desc_en: 'Earned 500 XP.',
    desc_ar: 'جمعت 500 نقطة خبرة.',
  },
  XP_1000: {
    icon: Star,
    tier: 'SILVER',
    category: 'xp',
    label_en: 'XP Hunter',
    label_ar: 'صياد الـ XP',
    desc_en: 'Earned 1,000 XP.',
    desc_ar: 'جمعت 1,000 نقطة خبرة.',
  },
  XP_5000: {
    icon: Gem,
    tier: 'GOLD',
    category: 'xp',
    label_en: 'XP Master',
    label_ar: 'سيد الـ XP',
    desc_en: 'Earned 5,000 XP.',
    desc_ar: 'جمعت 5,000 نقطة خبرة.',
  },
  XP_10000: {
    icon: Sparkles,
    tier: 'PLATINUM',
    category: 'xp',
    label_en: 'XP Legend',
    label_ar: 'أسطورة الـ XP',
    desc_en: 'Earned 10,000 XP.',
    desc_ar: 'جمعت 10,000 نقطة خبرة.',
  },
  XP_50000: {
    icon: Wand2,
    tier: 'DIAMOND',
    category: 'xp',
    label_en: 'XP God',
    label_ar: 'إله الـ XP',
    desc_en: 'Earned 50,000 XP.',
    desc_ar: 'جمعت 50,000 نقطة خبرة.',
  },

  // ─── Leaderboard & Time ──────────────────────────────────────────────────
  LEADERBOARD_1: {
    icon: Medal,
    tier: 'DIAMOND',
    category: 'leaderboard',
    label_en: '#1 Champion',
    label_ar: 'البطل الأول',
    desc_en: 'Reached #1 on the leaderboard.',
    desc_ar: 'تصدّرت قائمة المتصدرين.',
  },
  LEADERBOARD_TOP3: {
    icon: Award,
    tier: 'PLATINUM',
    category: 'leaderboard',
    label_en: 'Top Contender',
    label_ar: 'المنافس',
    desc_en: 'Ranked in the top 3 on the leaderboard.',
    desc_ar: 'وصلت لأعلى 3 في قائمة المتصدرين.',
  },
  LEADERBOARD_TOP10: {
    icon: Users,
    tier: 'GOLD',
    category: 'leaderboard',
    label_en: 'Elite Circle',
    label_ar: 'النخبة',
    desc_en: 'Ranked in the top 10 on the leaderboard.',
    desc_ar: 'وصلت لأعلى 10 في قائمة المتصدرين.',
  },
  TIME_LORD: {
    icon: Clock,
    tier: 'DIAMOND',
    category: 'leaderboard',
    label_en: 'Time Lord',
    label_ar: 'سيد الوقت',
    desc_en: 'Most time spent on the platform in a month.',
    desc_ar: 'أكثر وقت قضيته على المنصة في شهر واحد.',
  },
  MARATHON: {
    icon: Timer,
    tier: 'GOLD',
    category: 'leaderboard',
    label_en: 'Marathon',
    label_ar: 'الماراثون',
    desc_en: 'Accumulated 50+ total learning hours.',
    desc_ar: 'جمعت أكثر من 50 ساعة تعلم إجمالية.',
  },

  // ─── Special ─────────────────────────────────────────────────────────────
  EARLY_ADOPTER: {
    icon: Rocket,
    tier: 'GOLD',
    category: 'special',
    label_en: 'Early Adopter',
    label_ar: 'المبادر الأول',
    desc_en: 'One of the first 100 users on CyberLabs.',
    desc_ar: 'من أوائل 100 مستخدم على CyberLabs.',
  },
  NIGHT_OWL: {
    icon: Moon,
    tier: 'SILVER',
    category: 'special',
    label_en: 'Night Owl',
    label_ar: 'بومة الليل',
    desc_en: 'Studied after 11 PM for 7 consecutive days.',
    desc_ar: 'تعلّمت بعد الساعة 11 مساءً لـ7 أيام متتالية.',
  },
  EARLY_BIRD: {
    icon: Sun,
    tier: 'SILVER',
    category: 'special',
    label_en: 'Early Bird',
    label_ar: 'الطائر المبكر',
    desc_en: 'Studied before 7 AM for 7 consecutive days.',
    desc_ar: 'تعلّمت قبل الساعة 7 صباحاً لـ7 أيام متتالية.',
  },
  WEEKEND_WARRIOR: {
    icon: Gift,
    tier: 'BRONZE',
    category: 'special',
    label_en: 'Weekend Warrior',
    label_ar: 'محارب العطلة',
    desc_en: 'Active every weekend for a full month.',
    desc_ar: 'نشط في كل نهاية أسبوع لمدة شهر كامل.',
  },
  COMEBACK_KID: {
    icon: RefreshCcw,
    tier: 'SILVER',
    category: 'special',
    label_en: 'Comeback Kid',
    label_ar: 'العودة القوية',
    desc_en: 'Returned after 30 days away and completed a course.',
    desc_ar: 'رجعت للمنصة بعد 30 يوم غياب وأكملت كورساً.',
  },
  PIONEER: {
    icon: Fingerprint,
    tier: 'PLATINUM',
    category: 'special',
    label_en: 'Pioneer',
    label_ar: 'الرائد',
    desc_en: 'First user to solve a newly released lab.',
    desc_ar: 'أول مستخدم يحل لاباً جديداً.',
  },
  PERFECT_QUIZ: {
    icon: ClipboardCheck,
    tier: 'GOLD',
    category: 'special',
    label_en: 'Perfectionist',
    label_ar: 'المثالي',
    desc_en: 'Scored 100% on 5 different quizzes.',
    desc_ar: 'حصلت على 100% في 5 اختبارات مختلفة.',
  },
  SHARE_MASTER: {
    icon: Share2,
    tier: 'BRONZE',
    category: 'special',
    label_en: 'Community Voice',
    label_ar: 'صوت المجتمع',
    desc_en: 'Shared your profile 5 times.',
    desc_ar: 'شاركت ملفك الشخصي 5 مرات.',
  },
  PROFILE_COMPLETE: {
    icon: UserCheck,
    tier: 'BRONZE',
    category: 'special',
    label_en: 'Fully Armed',
    label_ar: 'مكتمل السلاح',
    desc_en: 'Completed your profile 100%.',
    desc_ar: 'أكملت بيانات ملفك الشخصي بنسبة 100%.',
  },
  DARK_MODE: {
    icon: EyeOff,
    tier: 'BRONZE',
    category: 'special',
    label_en: 'Dark Side',
    label_ar: 'الجانب المظلم',
    desc_en: 'Switched to dark mode. Welcome to the shadows.',
    desc_ar: 'فعّلت الوضع الداكن. أهلاً في الظلام.',
  },
  LANGUAGE_SWITCH: {
    icon: Languages,
    tier: 'BRONZE',
    category: 'special',
    label_en: 'Bilingual',
    label_ar: 'ثنائي اللغة',
    desc_en: 'Used the platform in both Arabic and English.',
    desc_ar: 'استخدمت المنصة بالعربي والإنجليزي.',
  },
};

export const UNKNOWN_BADGE_CONFIG: BadgeVisualConfig = {
  icon: ShieldCheck,
  tier: 'BRONZE',
  category: 'special',
  label_en: 'Badge',
  label_ar: 'وسام',
  desc_en: 'A special badge.',
  desc_ar: 'وسام مميز.',
};

export function getBadgeConfig(slug: string): BadgeVisualConfig {
  return (
    (BADGE_REGISTRY as Record<string, BadgeVisualConfig>)[slug] ??
    UNKNOWN_BADGE_CONFIG
  );
}

export const ALL_BADGE_SLUGS = Object.keys(BADGE_REGISTRY) as BadgeSlug[];
