import React from 'react';
import {
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldPlus,
  Search,
  Eye,
  Target,
  Crosshair,
  Flame,
  Zap,
  Globe,
  Terminal,
  Lock,
  Cpu,
  Network,
  Bug,
  Database,
  Cloud,
  Server,
  Wifi,
  Monitor,
  Code,
  Layers,
  Radio,
  Binary,
  Swords,
  Skull,
  Fingerprint,
  HardDrive,
  KeyRound,
  Radar,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const PATH_ICON_MAP: Record<string, LucideIcon> = {
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-plus': ShieldPlus,
  search: Search,
  eye: Eye,
  target: Target,
  crosshair: Crosshair,
  flame: Flame,
  zap: Zap,
  globe: Globe,
  terminal: Terminal,
  lock: Lock,
  cpu: Cpu,
  network: Network,
  bug: Bug,
  database: Database,
  cloud: Cloud,
  server: Server,
  wifi: Wifi,
  monitor: Monitor,
  code: Code,
  layers: Layers,
  radio: Radio,
  binary: Binary,
  swords: Swords,
  skull: Skull,
  fingerprint: Fingerprint,
  'hard-drive': HardDrive,
  key: KeyRound,
  radar: Radar,
};

export function resolvePathIcon(
  iconName: string,
  className?: string,
): React.ReactNode {
  const Icon = PATH_ICON_MAP[iconName?.toLowerCase()] ?? Shield;
  return <Icon className={className ?? 'h-6 w-6'} />;
}
